WHENEVER SQLERROR CONTINUE;

ALTER TABLE PROD01_DATA.TBEX1_USER_JSON
 DROP PRIMARY KEY CASCADE
/

DROP TABLE PROD01_DATA.TBEX1_USER_JSON CASCADE CONSTRAINTS
/

ALTER TABLE PROD01_DATA.TBEX1_COLLECTION_JSON
 DROP PRIMARY KEY CASCADE
/

DROP TABLE PROD01_DATA.TBEX1_COLLECTION_JSON CASCADE CONSTRAINTS
/


CREATE TABLE PROD01_DATA.TBEX1_USER_JSON
(
  USER_ID           NUMBER,
  NAME              VARCHAR2(300),
  COURSE            VARCHAR2(300),
  LEVEL_DISC        NUMBER,
  DEF               NUMBER ,
  ID_LAST_UPDATED   VARCHAR2(30),
  DTE_LAST_UPDATED  DATE,
  CONSTRAINT PK_TBEX1_USER_JSON PRIMARY KEY (USER_ID)
)
TABLESPACE CPSTABSML
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/

CREATE TABLE PROD01_DATA.TBEX1_COLLECTION_JSON
(
  COLLECTION_ID     NUMBER,
  USER_ID           NUMBER,
  BOOK              VARCHAR2(300),
  MUSIC             VARCHAR2(300),
  ID_LAST_UPDATED   VARCHAR2(30),
  DTE_LAST_UPDATED  DATE,
  CONSTRAINT PK_TBEX1_COLLECTION_JSON PRIMARY KEY (COLLECTION_ID),
  CONSTRAINT FK_TBEX1_COLLECTION_JSON_1 FOREIGN KEY (USER_ID)  REFERENCES PROD01_DATA.TBEX1_USER_JSON(USER_ID) ON DELETE SET NULL
)
TABLESPACE CPSTABSML
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/


CREATE SEQUENCE PROD01_DATA.SEQ_TBEX1_USER_JSON
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE SEQUENCE PROD01_DATA.SEQ_TBEX1_COLLECTION_JSON
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE OR REPLACE PUBLIC SYNONYM TBEX1_USER_JSON FOR PROD01_DATA.TBEX1_USER_JSON
/

CREATE OR REPLACE PUBLIC SYNONYM TBEX1_COLLECTION_JSON FOR PROD01_DATA.TBEX1_COLLECTION_JSON
/

CREATE OR REPLACE PUBLIC SYNONYM SEQ_TBEX1_USER_JSON FOR PROD01_DATA.SEQ_TBEX1_USER_JSON
/

CREATE OR REPLACE PUBLIC SYNONYM SEQ_TBEX1_COLLECTION_JSON FOR PROD01_DATA.SEQ_TBEX1_COLLECTION_JSON
/

GRANT DELETE, INSERT, SELECT, UPDATE ON PROD01_DATA.TBEX1_USER_JSON TO PROD01_CODE
/

GRANT DELETE, INSERT, SELECT, UPDATE ON PROD01_DATA.TBEX1_COLLECTION_JSON TO PROD01_CODE
/

GRANT SELECT ON PROD01_DATA.SEQ_TBEX1_USER_JSON TO PROD01_CODE
/

GRANT SELECT ON PROD01_DATA.SEQ_TBEX1_COLLECTION_JSON TO PROD01_CODE
/